/**************************************************************
	Table Name			: USP_PrescriptionHistory
	Purpose		        : Users Can see the Prescription generated by Doctors
	Created By          : Mani kumar
	Created On          : 09/08/24
	Modified By         :
	Modified ON         :
	MOdified            :

****************************************************************/
CREATE PROCEDURE USP_PrescriptionHistory
@AppointmentID INT
AS
BEGIN
	BEGIN TRY
		DECLARE @TempAppointmentID INT;
		--Checking input AppointmentID is available in prescriptions table or not
		SELECT @TempAppointmentID=[AppointmentID]
		FROM Prescriptions
		WHERE AppointmentID=@AppointmentID
		--If not existed or @Appointment is null , Raise an error
		IF (@TempAppointmentID IS NULL OR @AppointmentID IS NULL)
			BEGIN
				RAISERROR('Prescription is not available for specified Appointment',16,1);
				RETURN
			END
		--If Prescrption is available for that particular ID , Display Prescription history
		ELSE
		BEGIN
			SELECT P.AppointmentID , 
				   P.MedicineID , 
				   A.DoctorID ,
				   A.PatientID ,
				   A.SlotID, 
				   M.MedicineName,
				   P.Dosage ,
				   P.Instructions
			FROM Prescriptions p
			INNER JOIN Appointments A
			ON P.AppointmentID = A.AppointmentID
			INNER JOIN MedicineInventory M
			ON P.MedicineID = M.MedicinID
			WHERE A.AppointmentID=@AppointmentID
        END

	END TRY
	BEGIN CATCH
			DECLARE @ErrorMessage NVARCHAR(200),
            @ErrorSeverity INT,
            @ErrorState INT,
            @ErrorProcedure NVARCHAR(30),
            @ErrorLine INT,
            @ErrorNumber INT;

		SELECT @ErrorMessage = ERROR_MESSAGE(),
           @ErrorSeverity = ERROR_SEVERITY(),
           @ErrorState = ERROR_STATE(),
           @ErrorProcedure = ERROR_PROCEDURE(),
           @ErrorLine = ERROR_LINE(),
           @ErrorNumber = ERROR_NUMBER();

		EXEC USP_LogError @ErrorMessage, @ErrorSeverity, @ErrorState, @ErrorProcedure, @ErrorLine, @ErrorNumber;
	    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

    END CATCH
END

--Unit Testing

--Sending AppointmentID as NUll
--Expected output ,Throws an error
EXEC  USP_PrescriptionHistory NULL

--Sending Invalid AppointmentID 
--Expected output ,Throws an error
EXEC  USP_PrescriptionHistory 123

--Sending valid AppointmentID 
--Expected output ,Display the prescription History of specified AppointmentID
EXEC  USP_PrescriptionHistory 32
