/**************************************************************
	Table Name			: USP_AdminSalesMonitoring
	Purpose		        : Admins can monitor medicine sales based on specified date
	Created By          : Mani kumar
	Created On          : 12/08/24
	Modified By         :
	Modified ON         :
	Modified            :

****************************************************************/
ALTER PROCEDURE  USP_AdminSalesMonitoring
@Date VARCHAR(10),
@AdminID INT,
@Password VARCHAR(20),
@UserType VARCHAR(10)
AS
BEGIN
	BEGIN TRY
	--Checking if the input Date is exists in Order table or not
	IF (@UserType ='Admin')
	BEGIN
		EXEC USP_UserLogin 
				@UserID=@AdminID , 
				@UserType=@UserType,
				@Password=@Password
		
	END
	ELSE
	BEGIN
		RAISERROR('Only Admin can access this page',16,1);
		RETURN
	END
	DECLARE @TempDate VARCHAR(10);
	SELECT @TempDate = [OrderDate]
	FROM [Order]
	WHERE OrderDate = @Date
	--If Date Exists , Display the revenue generated by orders
	IF (@TempDate IS NOT NULL)
		BEGIN
			SELECT O.OrderID ,
				   SUM(O.TotalBill)AS TotalSales 
			FROM [Order] O
			WHERE OrderDate = @Date
			GROUP BY ROLLUP (O.OrderID )
		
		END
	ELSE
		BEGIN
			RAISERROR('No sales was registered on Specifed date',16,1);
			
		END
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(200),
				@ErrorSeverity INT,
				@ErrorState INT,
				@ErrorProcedure NVARCHAR(30),
				@ErrorLine INT,
				@ErrorNumber INT;

		SELECT @ErrorMessage = ERROR_MESSAGE(),
			   @ErrorSeverity = ERROR_SEVERITY(),
			   @ErrorState = ERROR_STATE(),
			   @ErrorProcedure = ERROR_PROCEDURE(),
			   @ErrorLine = ERROR_LINE(),
			   @ErrorNumber = ERROR_NUMBER();

		EXEC USP_LogError @ErrorMessage, @ErrorSeverity, @ErrorState, @ErrorProcedure, @ErrorLine, @ErrorNumber;
	    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
				

END
--Unit Testing

--Invalid Date
--Expected output 'Raise an error'
EXEC USP_AdminSalesMonitoring 
		@Date ='2024-08-19',
		@AdminID=1,
		@Password='HariHari',
		@UserType='Admin'

--valid Date
--Expected output 'Display the sales on specified date'
EXEC USP_AdminSalesMonitoring 
		@Date ='2024-08-20',
		@AdminID=1,
		@Password='HariHari',
		@UserType='Admin'

		SELECT * FROM Admin
		SELECT * FROM ErrorLog

	 
